"""
Check-in endpoint schemas.
Used to verify if a device is registered on app open.
"""
from pydantic import BaseModel, Field
from typing import Optional


class CheckInRequest(BaseModel):
    """Request schema for check-in endpoint."""
    device_id: str = Field(
        description="Unique device identifier obtained or generated by frontend"
    )


class CheckInResponse(BaseModel):
    """Response schema for check-in endpoint."""
    is_registered: bool = Field(
        description="Whether the device is registered in the system"
    )
    err_msg: Optional[str] = Field(
        default=None,
        description="Error message if any issue occurred"
    )
